//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_tracking_history
    {
        public int id { get; set; }
        public string GPS_id { get; set; }
        public System.DateTime date { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    }
}
