//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class household_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public household_master()
        {
            this.RFID_household_details = new HashSet<RFID_household_details>();
            this.route_household_details = new HashSet<route_household_details>();
        }
    
        public int id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string area { get; set; }
        public int pin_code { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string household_name { get; set; }
        public string email { get; set; }
        public decimal contact_no { get; set; }
        public int ward_id { get; set; }
        public System.DateTime valid_from { get; set; }
        public System.DateTime valid_to { get; set; }
        public int status { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_datetime { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_datetime { get; set; }
    
        public virtual ward_master ward_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFID_household_details> RFID_household_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<route_household_details> route_household_details { get; set; }
    }
}
