//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISWMS_master
    {
        public int id { get; set; }
        public int route_id { get; set; }
        public int driver_id { get; set; }
        public int truck_id { get; set; }
        public int scanner_id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan expected_start_time { get; set; }
        public System.TimeSpan expected_end_time { get; set; }
        public string status { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_datetime { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_datetime { get; set; }
    
        public virtual driver_master driver_master { get; set; }
        public virtual RFID_scanner_master RFID_scanner_master { get; set; }
        public virtual route_master route_master { get; set; }
        public virtual truck_master truck_master { get; set; }
    }
}
