//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFID_household_details
    {
        public int id { get; set; }
        public string RFID { get; set; }
        public string RFID_description { get; set; }
        public int household_id { get; set; }
        public string status { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_datetime { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_datetime { get; set; }
    
        public virtual household_master household_master { get; set; }
    }
}
