//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFID_scanner_history
    {
        public int id { get; set; }
        public string RFID_Scanner_Name { get; set; }
        public string RFID_number { get; set; }
        public System.DateTime Punching_date_time { get; set; }
        public System.DateTime created_datetime { get; set; }
    }
}
