//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck_tracking_history
    {
        public int ID { get; set; }
        public string truck_number { get; set; }
        public string status { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string speed { get; set; }
        public string Ignition { get; set; }
        public string packetdatetime { get; set; }
        public System.DateTime created_datetime { get; set; }
    }
}
