//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_security_access_details
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int module_id { get; set; }
        public int action_id { get; set; }
        public bool hasAccess { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_datetime { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_datetime { get; set; }
    
        public virtual actions_master actions_master { get; set; }
        public virtual module_master module_master { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
