//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class userType_modules
    {
        public int id { get; set; }
        public int user_type_id { get; set; }
        public int module_id { get; set; }
        public bool isActivie { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_datetime { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_datetime { get; set; }
    
        public virtual module_master module_master { get; set; }
        public virtual userType_master userType_master { get; set; }
    }
}
