//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_master()
        {
            this.user_security_access_details = new HashSet<user_security_access_details>();
            this.ward_master = new HashSet<ward_master>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string name { get; set; }
        public int user_type { get; set; }
        public bool isActive { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_datetime { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_datetime { get; set; }
        public string password { get; set; }
        public string email_id { get; set; }
        public Nullable<decimal> contact_no { get; set; }
        public string photo { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string area { get; set; }
    
        public virtual userType_master userType_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_security_access_details> user_security_access_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ward_master> ward_master { get; set; }
    }
}
