//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISWM.WEB.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward_Karyakrta_master
    {
        public int id { get; set; }
        public int ward_id { get; set; }
        public int area_id { get; set; }
        public int karyakarta_id { get; set; }
        public int status { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_datetime { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_datetime { get; set; }
    
        public virtual area_master area_master { get; set; }
        public virtual user_master user_master { get; set; }
        public virtual ward_master ward_master { get; set; }
    }
}
